export { default as Home } from './Home'
export { default as Movies } from './Movies'
export { default as MoviesSearch } from './MoviesSearch'
export { default as MovieDetail } from './MovieDetail'
export { default as Error } from './Error'